apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifesub-web
  namespace: dg0420-lifesub-ns
  labels:
    app: lifesub-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifesub-web
  template:
    metadata:
      labels:
        app: lifesub-web
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: lifesub-web
        image: acrdigitalgarage03.azurecr.io/dg0420/lifesub-web:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
        volumeMounts:
        - name: runtime-config
          mountPath: /usr/share/nginx/html/runtime-env.js
          subPath: runtime-env.js
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
      volumes:
      - name: runtime-config
        configMap:
          name: lifesub-web-config
